# Options for the Chef Installer.

# Public cookbook repo. (Full URL)
chef_cookbook_repos: https://github.com/aenimal/openstack_cookbooks/tarball/master

# Shared Chef cookbook repository hosted in Rackspace Cloud Files.
#chef_cookbook_repos: CookbookRepos/cookbook-repo1.tar.gz

# Optionally you can specify multiple repos:
#chef_cookbook_repos:
#- CookbookRepos/cookbook_repo1-1.1.tar.gz
#- CookbookRepos/cookbook_repo2-trunk.tar.gz

# The Chef JSON configuration contains attributes and recipes for nodes.
chef_json_file: config/nodes.json

#databags_json_file: config/databags.json

# Chef server name
chef_server_name: login
